### ISSUE TITLE
Unexpected Request Failure

### ISSUE THREAD

**Issue by producktivemary** [resurfaceio/insomnia-plugin#3]
Hello! 
My colleagues and I all get the same error while using the plugin. Whenever we try to make a request having the plugin installed, we get following error:
Unexpected Request FailureThe request failed due to an unhandled error:

Error: Failed to transform request with plugins: req_39863bdefae84aa5ae1418a96cc50af5

Thank you in advance.

**Comment by nst-coppertree** [comment]
Yes, same issue. Unable to use the plugin. @RobDickinson @monrax Please let us know, what information would be required to debug the issue.

**Comment by monrax** [comment]
Howdy! Thank you for bringing this up. The specific error message is no longer shown in the response preview panel, but it looks like this is the same issue as https://github.com/Kong/insomnia/issues/5078

We are in the process of making a new release that fixes this issue. It should be available by the end of ~this~ next week.

**Comment by monrax** [comment]
Hi, @producktivemary @nst-coppertree 👋
I'm happy to report that the dependency causing the issue ([resurfaceio-logger](https://www.npmjs.com/package/resurfaceio-logger/v/2.2.2)) has been patched! Please, reinstall the plugin at your earliest convenience.

I believe this issue can be closed, but do let us know if you're still experiencing the problem and we should be able to reopen it.

Thanks!
